#!/bin/sh

[ -z "$SET_HOSTNAME" ] && SET_HOSTNAME=freebsd

gen_host() {
    echo "==> Adding host to /etc/hosts"
    echo "$ETH0_IP $SET_HOSTNAME" >> /etc/hosts
    echo "$ETH0_IP6 $SET_HOSTNAME" >> /etc/hosts
}

gen_host
