#!/bin/sh
nameservers="$ETH0_DNS $ETH1_DNS $ETH2_DNS"
[ -z "$nameservers" ] && exit 0

: > /etc/resolv.conf

for nameserver in $nameservers; do
    echo nameserver $nameserver >> /etc/resolv.conf
done

