#!/bin/sh

[ -z "$SET_HOSTNAME" ] && SET_HOSTNAME=freebsd

set_hostname() {
    sysrc -q hostname="$SET_HOSTNAME" > /dev/null
    hostname $SET_HOSTNAME
}

if [ -n "$SET_HOSTNAME" ]; then
   set_hostname
fi
